apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mygovbc-service-provider-tools-deploy
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: mygovbc-sp-app
    name: mygovbc-sp-app
  spec:
    replicas: 1
    selector:
      deploymentconfig: mygovbc-sp-app
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mygovbc-sp-app
          deploymentconfig: mygovbc-sp-app
      spec:
        containers:
        - env:
          - name: POSTGRESQL_SERVICE_HOST
            value: postgresql
          - name: POSTGRESQL_SERVICE_PORT
            value: "5432"
          - name: POSTGRESQL_DATABASE
            value: pds
          - name: POSTGRESQL_SSD_USER
            value: ssd
          - name: POSTGRESQL_SSD_PASSWORD
            value: changeme
          - name: POSTGRESQL_ORBEON_USER
            value: orbeon
          - name: POSTGRESQL_ORBEON_PASSWORD
            value: changeme
          - name: OPENSHIFT_SMTP_HOST
            value: apps.smtp.gov.bc.ca
          - name: SSD_CONFIGURATION
            value: /opt/app-root/src/config
          - name: ORBEON_CONFIGURATION
            value: /opt/app-root/src/config
          image: mygovbc-sp-app
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /orbeon/home/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: mygovbc-sp-app
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /orbeon/home/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 3Gi
            requests:
              cpu: 200m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/app-root/src/config
            name: volume-bxbac
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: sp-app
          name: volume-bxbac
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mygovbc-sp-app
        from:
          kind: ImageStreamTag
          name: mygovbc-sp-app:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: mygovbc-sp-app
    name: postgresql
  spec:
    replicas: 1
    selector:
      name: postgresql
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 9999
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: postgres
          - name: POSTGRESQL_PASSWORD
            value: changeme
          - name: POSTGRESQL_DATABASE
            value: pds
          - name: POSTGRESQL_ORBEON_USER
            value: orbeon
          - name: POSTGRESQL_ORBEON_PASSWORD
            value: changeme
          - name: POSTGRESQL_SSD_USER
            value: ssd
          - name: POSTGRESQL_SSD_PASSWORD
            value: changeme
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:9.5
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mygovbc-sp-app
    name: rproxy
  spec:
    replicas: 2
    selector:
      app: mygovbc-sp-app
      deploymentconfig: rproxy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: mygovbc-sp-app
          deploymentconfig: rproxy
      spec:
        containers:
        - env:
          - name: NGINX_PROXY_HOST
            value: 
          image: nginx-reverse-proxy
          imagePullPolicy: Always
          name: rproxy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - rproxy
        from:
          kind: ImageStreamTag
          name: nginx-reverse-proxy:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: mygovbc-sp-app
    name: mygovbc-sp-app
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nginx-reverse-proxy
    labels:
      app: mygovbc-sp-app
- apiVersion: v1
  data:
    SSDconfig.properties: ''
    cmfOrbeonFilter.properties: ''
    emailmessages.properties: ''
  kind: ConfigMap
  metadata:
    name: sp-app
    labels:
      app: mygovbc-sp-app
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      service.alpha.openshift.io/dependencies: '[{"name":"mygovbc-sp-app-admin","namespace":"","kind":"Service"}]'
    labels:
      app: mygovbc-sp-app
    name: mygovbc-sp-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: mygovbc-sp-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: mygovbc-sp-app
    name: mygovbc-sp-app-admin
  spec:
    ports:
    - port: 9990
      protocol: TCP
      targetPort: 9990
    selector:
      deploymentconfig: mygovbc-sp-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mygovbc-sp-app
    name: postgresql
  spec:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: postgresql
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mygovbc-sp-app
    name: rproxy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mygovbc-sp-app
      deploymentconfig: rproxy
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 9999d
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: mygovbc-sp-app
    name: mygovbc-sp-app
  spec:
    host:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: mygovbc-sp-app
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: mygovbc-sp-app
    name: mygovbc-sp-app-admin
  spec:
    host:
    to:
      kind: Service
      name: mygovbc-sp-app-admin
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: mygovbc-sp-app
    name: rproxy
  spec:
    host:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: rproxy
      weight: 100
    wildcardPolicy: None
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      app: mygovbc-sp-app
    name: postgresql
  spec:
    maxReplicas: 1
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: DeploymentConfig
      name: postgresql
    targetCPUUtilizationPercentage: 80
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: mygovbc-sp-app
    name: postgresql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
